### PR TITLE
Multi-order map implementation

### LINKED ISSUE #11: Support multi-order Healpix value maps
It would be great if the package could support a generalized version of MOC, which would support any arbitrary value types. It would also be interesting to have some tooling to support different strategies for tile merging and splitting.

I have some implementation of this idea in [this repo](https://github.com/hombit/mom-builder), and would be happy to port that code to this project. If it sounds good to you, I'll open a draft PR, and ask you to review it and open some fine-grained issues.

### PR DESCRIPTION
**Pull request by hombit**
Implementation of multi-order healpix value maps for nested scheme. It starts with almost complete copy-paste from https://github.com/hombit/mom-builder, but without Python code and bindings.

I understand that a lot of changes are needed (and probably not all the functionality is needed), but I believe that it would be easier to discuss the scope of these changes having the code we can comment.

It is not finished yet and It is supposed to eventually close #11.

### CODE REVIEW

**Comment by fxpineau** [comment]
Would you put your code in `nested:::map::mom::impls::xxx` in which `xxx` would be a (directory) module that could be names e.g. `hierach` (or any other name you would give)?

**Comment by hombit** [comment]
@fxpineau I'm ready to do much more than that before we can merge this. I would like to know the following:

1. What functionality do you want, and **don't want**, to be included?
2. I remember you proposed changing the layout of the MOM structure to make it "flat" ([this mom-builder issue](https://github.com/hombit/mom-builder/issues/2)). Could you please point me to the structures or traits I can use or take inspiration from?

Could you please comment on the PR at the file or `struct`/`trait` level to address these questions? Do I need to include a summary of the code I’ve added here?

**Comment by hombit** [comment]
Never mind, I missed this comment: https://github.com/cds-astro/cds-healpix-rust/issues/11#issuecomment-2376369284

I'll start porting the code to support the abstractions you introduced! (With a stretched timeline, sorry in advance if it takes a while)

**Comment by fxpineau** [comment]
@hombit 
I made a "single vec based" implementation of skymap to mom, see [here](https://github.com/cds-astro/cds-healpix-rust/commit/152058d986444994636e6826f30cc4c9fb2f19af#diff-ccfa7c39cd6d39a204549499e02e11c454aa2b883c51dbc3c026c2103882031b).
It would be nice to add your own implementation (even before you implemented the abstractions) and possibly compare both approaches.

**Comment by hombit** [comment]
@fxpineau Thank you! Sorry for the delay, I haven’t had a chance to work on it yet. I’m going to push it forward today.

**Comment by fxpineau** [comment]
When you go out of the Draft mod, I merge your PR.

**Pull request merged**
